.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ARINU" "1" "October 2012" "" ""
.
.SH "NAME"
\fBarinu\fR \- ARINr Utility Command
.
.SH "SYNOPSIS"
arinu COMMAND
.
.SH "DESCRIPTION"
This program performs maintenance tasks for the ARINr suite of commands\.
.
.SH "COMMANDS"
.
.IP "\(bu" 4
\fBhelp\fR Shows a help screen\.
.
.IP "\(bu" 4
\fBclean_cache\fR Forces the cleaning of the arinw(1) cache\.
.
.IP "\(bu" 4
\fBcache_count\fR Reports the number of files in the arinw(1) cache\.
.
.IP "\(bu" 4
\fBcached_last\fR Shows details on the last file cached\.
.
.IP "\(bu" 4
\fBconfig\fR Show the interpretted configuration for ARINr commands\.
.
.IP "" 0
.
.SH "SEE ALSO"
arinr(7), arinw(1)
