.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ARININFO" "1" "October 2012" "" ""
.
.SH "NAME"
\fBarininfo\fR \- ARINr Whois Command
.
.SH "SYNOPSIS"
arininfo \fIoptions\fR QUERY_VALUE
.
.SH "DESCRIPTION"
This program uses ARIN\'s Whois\-RWS(7) RESTful API to query ARIN\'s Whois database\. The general usage is "arininfo QUERY_VALUE" where the type of QUERY_VALUE influences the type of query performed\. This program will attempt to guess the type of QUERY_VALUE, but the QUERY_VALUE type maybe explicitly set using the \fB\-t\fR option\. Queries for data related to the QUERY_VALUE may be specified using the \fB\-r\fR option (i\.e\. the reverse DNS delegations related to a network)\.
.
.P
In certain cases, Organization handles (orghandle), also knows as organization ids, can be properly determined\. This occurs when the Organization handle ends with \fI\-z\fR or with \fI\-xxx\fR where xxx is a number\. As a shortcut for Organization handles that do not match these cases, a \fI\-o\fR can be appended to signify that it is an Organization handle\.
.
.P
The following are other criteria for determining the type of the QUERY_VALUE when the \fB\-t\fR option is not given:
.
.IP "\(bu" 4
If the QUERY_VALUE is simply a number, it is assumed to be an Autonomous System Number\.
.
.IP "\(bu" 4
If the QUERY_VALUE is a number prepended with "AS", it is assumed to be an Autonomous System Number\.
.
.IP "\(bu" 4
If the QUERY_VALUE begins with "NET\-" or "NET6\-" it is assumed to be a network handle\.
.
.IP "\(bu" 4
If the QUERY_VALUE appears to be an IPv4 or IPv6 address, then it is assumed to be an IP address\.
.
.IP "\(bu" 4
If the QUERY_VALUE ends in "in\-addr\.arpa" or "ip6\.arpa", it is assumed to be a reverse DNS delegation point\.
.
.IP "\(bu" 4
If the QUERY_VALUE appears to be a proper name, it is assumed to be a name of a Point of Contact\.
.
.IP "" 0
.
.P
The QUERY_VALUE can also be a result value from a previous query if it ends with an equal sign ("=")\. Consider the following tree output:
.
.P
1= NET\-192\-136\-136\-0\-1 ( 192\.136\.136\.0 \- 192\.136\.136\.255 )
.
.br
`\-\-\- 1\. Reverse DNS Delegations
.
.IP "" 4
.
.nf

    `\-\-\- 1= 136\.136\.192\.in\-addr\.arpa\.
.
.fi
.
.IP "" 0
.
.P
A QUERY_VALUE of "1=1=1=" would be a shortcut for requerying for 136\.136\.192\.in\-addr\.arpa\. The character between the numbers can also be a period character ("\.")\. So "1\.1\.1=" would be equivalent\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-r\fR, \fB\-\-related\fR TYPE
.
.br
Query for the specified type related to the query value: \fBnets\fR for query for the related networks, \fBdels\fR for query for the reverse DNS delegations, \fBorgs\fR for query for the related organizations, \fBpocs\fR for query for the related points of contact, \fBasns\fR for query for the related autonomous system numbers
.
.IP "\(bu" 4
\fB\-t\fR, \fB\-\-type\fR TYPE
.
.br
Specify type of the query value: \fBnethandle\fR for network handle, \fBpochandle\fR for point of contact handle, \fBorghandle\fR for organization handle, \fBip4addr\fR for IPv4 address, \fBip6addr\fR for IPv6 address, \fBip4cidr\fR for IPv4 cidr block, \fBip6cidr\fR for IPv6 cidr block, \fBasnumber\fR for autonomous system number, \fBdelegation\fR for reverse DNS delegation, \fBpocname\fR for name of a point of contact, \fBorgname\fR for name of an organization, \fBresult\fR for result from a previous query
.
.IP "\(bu" 4
\fB\-\-pft\fR YES|NO|TRUE|FALSE
.
.br
Use a PFT style query\.
.
.IP "\(bu" 4
\fB\-\-cidr\fR LESS|EXACT|MORE
.
.br
Type of matching to use for CIDR queries\.
.
.IP "\(bu" 4
\fB\-\-substring\fR YES|NO|TRUE|FALSE
.
.br
Use substring matching for name searches\.
.
.IP "\(bu" 4
\fB\-\-details\fR YES|NO|TRUE|FALSE
.
.br
Query for extra details\.
.
.IP "\(bu" 4
\fB\-U\fR, \fB\-\-url\fR URL
.
.br
The base URL of the Whois\-RWS(7) system\.
.
.IP "\(bu" 4
\fB\-\-cache\-expiry\fR SECONDS
.
.br
Age in seconds of items in the cache to be considered expired\.
.
.IP "\(bu" 4
\fB\-\-cache\fR YES|NO|TRUE|FALSE
.
.br
Controls if the cache is used or not\.
.
.IP "\(bu" 4
\fB\-\-messages\fR MESSAGE_LEVEL
.
.br
Specify one of the message levels: \fBnone\fR for no messages are to be output, \fBsome\fR for some messages to be output, or \fBall\fR for all messages to be output\.
.
.IP "\(bu" 4
\fB\-\-messages\-out\fR FILE
.
.br
Specifies that messages are to be written to the given file\.
.
.IP "\(bu" 4
\fB\-\-data\fR DATA_AMOUNT
.
.br
Specifies the amount of data to be output\. Use of of: \fBterse\fR, \fBnormal\fR, or \fBextra\fR\.
.
.IP "\(bu" 4
\fB\-\-data\-out\fR FILE
.
.br
File where data is to be written if specified\.
.
.IP "\(bu" 4
\fB\-V\fR
.
.br
Equivalent to \fB\-\-messages all\fR and \fB\-\-data extra\fR
.
.IP "\(bu" 4
\fB\-h\fR
.
.br
Displays help\.
.
.IP "" 0
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
\fBarininfo kosters\fR queries for a POC with the last name of "Kosters"\.
.
.IP "\(bu" 4
\fBarininfo 2=\fR queries for the second value in a result from the previous query\.
.
.IP "\(bu" 4
\fBarininfo \-t orghandle arin\fR queries for organizations with the handle "arin"\.
.
.IP "\(bu" 4
\fBarininfo arin\-o\fR is the same as above\.
.
.IP "\(bu" 4
\fBarininfo 192\.136\.136\.51\fR queries for the most specific network enclosing 192\.136\.136\.51\.
.
.IP "" 0
.
.SH "SEE ALSO"
arinr(7), arinutil(1), Whois\-RWS(7)
