.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RDNS" "1" "February 2013" "" ""
.
.SH "NAME"
\fBrdns\fR \- ARINcli Reverse DNS
.
.SH "SYNOPSIS"
rdns \fIoptions\fR \-\-edit DELEGATION_NAME
.
.br
rdns \fIoptions\fR \-\-zonefile ZONE_FILE1 [ZONE_FILE2, \.\.\.\.]
.
.SH "DESCRIPTION"
This program uses ARIN\'s Reg\-RWS(7) service to modify reverse DNS delegations\.
.
.P
There are two actions specified with either the \-\-edit or \-\-zonefile options\.
.
.P
The \-\-edit option requires the name of a reverse DNS delegation name (or zone) as an argument\. It will fetch that delegation from ARIN and allow the user to edit it in a YAML file and then modify the delegation in ARIN\'s database if the YAML file has been modified\.
.
.P
When the editor is invoked, if no changes are made (i\.e\. the editor quits without saving), then the action will be aborted\.
.
.P
The \-\-zonefile option takes one or more zone file names as arguments\. It will parse the zone files and modify the corresponding reverse DNS delegations based on the zone files\. If the \-\-no\-verify is not specified, the delegation information will be put into a YAML file and the user will be allowed to edit it before the delegations are modified\.
.
.P
Unlike the \-\-edit action, when the \-\-zonefile action invokes the editor, the actions will be performed even if no changes are made\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-\-edit DELEGATION_NAME\fR Retrieves the reverse DNS information for editing, and then submits the modifications\.
.
.IP "\(bu" 4
\fB\-\-zonefile ZONEFILES\.\.\.\fR Parses DNS zone files and modifies the reverse DNS delegation information accordingly\.
.
.IP "\(bu" 4
`\-\-no\-verify When used in conjuction with the \-\-zonefile action, it instructs the program to bypass the editing/verification phase and to modify the reverse DNS information immediately after parsing\.
.
.IP "\(bu" 4
\fB\-A\fR, \fB\-\-apikey\fR API_KEY The API_KEY to use\. API Keys are associated with ARIN Online accounts and are the methods used for authentication in Reg\-RWS(7)\.
.
.IP "\(bu" 4
\fB\-U\fR, \fB\-\-url\fR URL
.
.br
The base URL of the Reg\-RWS(7) system\.
.
.IP "\(bu" 4
\fB\-\-messages\fR MESSAGE_LEVEL
.
.br
Specify one of the message levels: \fBnone\fR for no messages are to be output, \fBsome\fR for some messages to be output, or \fBall\fR for all messages to be output\.
.
.IP "\(bu" 4
\fB\-\-messages\-out\fR FILE
.
.br
Specifies that messages are to be written to the given file\.
.
.IP "\(bu" 4
\fB\-\-data\fR DATA_AMOUNT
.
.br
Specifies the amount of data to be output\. Use of of: \fBterse\fR, \fBnormal\fR, or \fBextra\fR\.
.
.IP "\(bu" 4
\fB\-\-data\-out\fR FILE
.
.br
File where data is to be written if specified\.
.
.IP "\(bu" 4
\fB\-V\fR
.
.br
Equivalent to \fB\-\-messages all\fR and \fB\-\-data extra\fR
.
.IP "\(bu" 4
\fB\-h\fR
.
.br
Displays help\.
.
.IP "" 0
.
.SH "SEE ALSO"
arincli(7), Reg\-RWS(7)
