.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TICKET" "1" "February 2013" "" ""
.
.SH "NAME"
\fBticket\fR \- ARINcli ticket Command
.
.SH "SYNOPSIS"
ticket \fIoptions\fR \-\-check [TICKET_NUMBER]
.
.br
ticket \fIoptions\fR \-\-update [TICKET_NUMBER]
.
.br
ticket \fIoptions\fR \-\-show [TICKET_NUMBER] [DETACH_FILE]
.
.br
ticket \fIoptions\fR \-\-remove [TICKET_NUMBER]
.
.br
ticket \fIoptions\fR \-\-message[=MESSAGE_FILE] TICKET_NUMBER
.
.SH "DESCRIPTION"
This program uses ARIN\'s Reg\-RWS(7) RESTful API to download tickets, display tickets, and add messages to tickets\.
.
.P
The \fB\-\-check\fR command option checks the internal ticket database against data in Reg\-RWS(7) and displays ticket numbers for any tickets that have been updated\. If a ticket number is given, then only that ticket will be checked\. If no ticket number is given, then all tickets will be checked\.
.
.P
The \fB\-\-update\fR command option downloads tickets to the internal ticket database from Reg\-RWS(7)\. If a ticket number is given, then only that ticket will be downloaded\. If no ticket number is given, then all tickets will be downloaded\. By default, tickets or messages or attachments will not be downloaded if they have already been downloaded or do not need to be updated\. However, the \fB\-\-force\-update\fR option may be used to force downloading when an update would not do so otherwise\.
.
.P
The \fB\-\-show\fR command option displays tickets from the internal ticket database\. If no ticket number is given, a tree summary of all the tickets in the database will be displayed\. If a ticket number is given, a tree summary for that specific ticket will be display along with all messages on that ticket\.
.
.P
The \fB\-\-remove\fR command option removes tickets from the internal ticket database\. If no ticket number is given, all tickets will be removed\. If a ticket number is given, just that ticket will be removed\.
.
.P
The \fB\-\-message\fR command option sends a message to Reg\-RWS(7) to attach to a ticket\. The \fB\-f\fR or \fB\-\-file\fR parameters can be used to specify a file to be attached as the message\. If no message file is specified, an editor will be invoked so that the user can create the message\.
.
.SH "TREE ADDRESSES"
All the commands will produce a tree of results in the same way as arininfo(1)\. Numbered items in the tree with a trailing equal sign ("=") are addressable\. Consider the following tree:
.
.P
1= 20121018\-X1
.
.br
|\-\-\- 1= How does Whois Work
.
.br
|\-\-\- 2= Ticket Status Update
.
.br
|\-\-\- 3= Ticket Status Update
.
.br
|\-\-\- 4= IP Addresses/AS Numbers \- test \- ANSWERED
.
.br
|\-\-\- 5= Ticket Status Update
.
.br
|\-\-\- 6= Ticket Status Update
.
.br
|\-\-\- 7= (no subject)
.
.br
| |\-\-\- 1= sac\-055\-en\.pdf
.
.br
|\-\-\- 8= IP Addresses/AS Numbers \- test \- ANSWERED
.
.br
| |\-\-\- 1= my_cat\.jpg
.
.br
| |\-\-\- 2= kitty_litter_disposal\.pdf
.
.br
|\-\-\- 9= Ticket Status Update
.
.br
|\-\- 10= Ticket Status Update
.
.br
`\-\- 11= (no subject)
.
.P
In the above example, 1= is a tree address for ticket 20121018\-X1\. Nodes in the tree can be separated by an ("=") sign or a dot ("\.")\. Therefore 1\.1= addresses the first message of ticket 20121018\-X1, 1\.2= address the second message of that ticket, and so on\.
.
.P
When using \fB\-s\fR or \fB\-\-show\fR to view a ticket, narrowing down a single message on the ticket will display only that message\. In the example above \fBticket \-s 1\.1=\fR would display only the message with the subject "How does Whois Work"\.
.
.P
Attachments can be copied out of the ticket by narrowing the tree address to an attachment\. For example, \fBticket \-s 1\.7\.1=\fR would create a copy of sac\-055\-en\.pdf in the current directory\. The destination name and location can be changed by adding a trailing file name\. For example, \fBticket \-s 1\.7\.1= /tmp/some\.pdf\fR sound copy the attachment sac\-055\-en\.pdf to a file named some\.pdf in the /tmp directory\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-c\fR, \fB\-\-check\fR [TICKET_NUMBER]
.
.br
Checks for updated tickets\. If no ticket number is given, all tickets are checked\.
.
.IP "\(bu" 4
\fB\-u\fR, \fB\-\-update\fR [TICKET_NUMBER]
.
.br
Updates tickets\. If no ticket number is given, all tickets are updated\.
.
.IP "\(bu" 4
\fB\-\-force\-update\fR
.
.br
Forces an update not to skip the downloading of any attachments or messages or tickets\.
.
.IP "\(bu" 4
\fB\-s\fR, \fB\-\-show\fR [TICKET_NUMBER]
.
.br
Shows ticket information\. If no ticket number is given, a summary tree of all tickets will be shown\.
.
.IP "\(bu" 4
\fB\-m\fR, \fB\-\-message\fR TICKET_NUMBER Sends a message to be attached to a ticket\.
.
.IP "\(bu" 4
\fB\-f\fR, \fB\-\-file\fR
.
.br
Uses a file instead of invoking an editor for the message to attach to a ticket\.
.
.IP "\(bu" 4
\fB\-A\fR, \fB\-\-apikey\fR API_KEY
.
.br
The API_KEY to use\. API Keys are associated with ARIN Online accounts and are the methods used for authentication in Reg\-RWS(7)\.
.
.IP "\(bu" 4
\fB\-U\fR, \fB\-\-url\fR URL
.
.br
The base URL of the Reg\-RWS(7) system\.
.
.IP "\(bu" 4
\fB\-\-messages\fR MESSAGE_LEVEL
.
.br
Specify one of the message levels: \fBnone\fR for no messages are to be output, \fBsome\fR for some messages to be output, or \fBall\fR for all messages to be output\.
.
.IP "\(bu" 4
\fB\-\-messages\-out\fR FILE
.
.br
Specifies that messages are to be written to the given file\.
.
.IP "\(bu" 4
\fB\-\-data\fR DATA_AMOUNT
.
.br
Specifies the amount of data to be output\. Use of of: \fBterse\fR, \fBnormal\fR, or \fBextra\fR\.
.
.IP "\(bu" 4
\fB\-\-data\-out\fR FILE
.
.br
File where data is to be written if specified\.
.
.IP "\(bu" 4
\fB\-V\fR
.
.br
Equivalent to \fB\-\-messages all\fR and \fB\-\-data extra\fR
.
.IP "\(bu" 4
\fB\-h\fR
.
.br
Displays help\.
.
.IP "" 0
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
\fBticket 20121018\-X1\fR shows the ticket 20121018\-X1\.
.
.IP "\(bu" 4
\fBticket \-s 20121018\-X1\fR does the same as above\.
.
.IP "\(bu" 4
\fBticket \-s 1=\fR shows the ticket in the tree addressed by 1=\.
.
.IP "\(bu" 4
\fBticket \-u\fR updates all the tickets in the internal ticket database\.
.
.IP "" 0
.
.SH "SEE ALSO"
arincli(7), arinutil(1), arininfo(1), Reg\-RWS(7)
